# Generated by Django 4.2.5 on 2023-09-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "auctions",
            "0003_alter_bid_user_alter_comment_item_alter_listing_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
