# Generated by Django 4.2.5 on 2023-09-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_alter_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={
                "ordering": ["-price"],
                "verbose_name": "Bid",
                "verbose_name_plural": "Bids",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="listing",
            options={
                "ordering": ["-created"],
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings",
            },
        ),
        migrations.AlterModelOptions(
            name="watchlist",
            options={
                "ordering": ["user"],
                "verbose_name": "WatchList",
                "verbose_name_plural": "WatchLists",
            },
        ),
        migrations.AlterField(
            model_name="listing",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
