# Generated by Django 4.2.5 on 2023-09-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_bid_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="followed",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="followed_last_day",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
