# Generated by Django 4.2.5 on 2023-10-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_alter_listing_followed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
