# Generated by Django 4.2.5 on 2023-10-07 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_listing_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={
                "ordering": ["price"],
                "verbose_name": "Bid",
                "verbose_name_plural": "Bids",
            },
        ),
        migrations.AddField(
            model_name="watchlist",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
