# Generated by Django 4.2.5 on 2023-10-07 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_alter_bid_options_watchlist_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="followed_last_day",
        ),
    ]
