# Generated by Django 4.2.5 on 2023-10-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_remove_listing_followed_last_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auctions.listing"
            ),
        ),
    ]
