# Generated by Django 4.2.5 on 2023-10-08 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_alter_watchlist_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={
                "ordering": ["-price"],
                "verbose_name": "Bid",
                "verbose_name_plural": "Bids",
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_winner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
