# Generated by Django 4.2.5 on 2023-10-08 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_comment_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
    ]
